#!/usr/bin/env python3
"""
Honest attempt to DERIVE 5/27/68 from cascade's first principles.

Observed: Omega_o = 0.0493, Omega_DM = 0.265, Omega_DE = 0.686 (Planck 2018)
Current best: Omega_o = 1/20 = 0.05, Omega_DM = 3/11 = 0.2727, Omega_DE = 0.6773
(but is a fit, not statistically significant per commit 58)

This script tries SEVERAL physical approaches to derive 5/27/68:
1. Pure dimensional-inversion kinematics
2. Geometric / dimensional argument
3. Cascade-level dynamics (cumulative event budgets)
4. Information-theoretic / entropy partition
5. Growth-factor + universal-split consistency

For each, we either get a number or conclude that the approach
needs additional information not provided by the cascade alone.
The honest answer may be "the cascade doesn't uniquely derive 5/27/68
without specifying the 4D event's properties" - and that's OK to say.
"""

import math
import sys
sys.path.insert(0, ".")
sys.path.insert(0, "calculations")

from cascade_model import Constants


def hr(ch="="):
    print()
    print(ch * 78)
    print(ch * 78)


def main():
    hr()
    print("ATTEMPT TO DERIVE 5/27/68 FROM CASCADE'S FIRST PRINCIPLES")
    hr()

    print(f"\n  Observed (Planck 2018):")
    print(f"    Omega_o = 0.0493 (ordinary matter)")
    print(f"    Omega_DM = 0.265 (dark matter)")
    print(f"    Omega_DE = 0.686 (dark energy)")
    print()
    print(f"  Cascade's framework:")
    print(f"    - 4D event -> 3+1D universe (the universe we observe)")
    print(f"    - 3+1D events -> 2D universes (children)")
    print(f"    - 2D universes' back-projection -> DM in 3+1D (per cascade)")
    print(f"    - 4D event's antigravity -> DE in 3+1D (per cascade)")
    print(f"    - G_2D ~ 1e8 (growth factor for 2D universes)")
    print()
    print(f"  Question: from these, can we DERIVE 5/27/68?")

    # =========================================================================
    # Approach 1: Dimensional projection kinematics
    # =========================================================================
    print(f"\n\n  APPROACH 1: Dimensional projection kinematics")
    print(f"  {'-'*70}")
    print(f"  In a 4D -> 3+1D projection, the 4D event's energy E_4D")
    print(f"  is partitioned into:")
    print(f"    - Direct projection to 3+1D: E_3plus1D (matter + radiation)")
    print(f"    - Cascade residue (vacuum): E_DE")
    print(f"    - Indirect via 2D universes: E_2D (which back-projects to DM)")
    print()
    print(f"  We have: E_4D = E_3plus1D + E_DE + E_2D_residue")
    print(f"  In energy-density units (Omega):")
    print(f"    Omega_o + Omega_DM + Omega_DE = 1")
    print()
    print(f"  Question: what's the 4D -> 3+1D projection fraction f_3plus1D?")
    print()
    print(f"  In a simple 4D->3+1D projection, the 'lost' dimension is 1/4")
    print(f"  of the 4D phase space. So f_3plus1D = 3/4 = 0.75?")
    print()
    print(f"  If f_3plus1D = 0.75:")
    print(f"    5% matter + 27% DM = 32% (projected to 3+1D)")
    print(f"    68% DE = 4D residue")
    print()
    print(f"  But: 0.75 != 0.32. So this approach doesn't directly work.")
    print()
    print(f"  Maybe: 32% is the *fraction that projects to ENERGETIC 3+1D*")
    print(f"  (creates particles), while 68% is the *kinematic residue*")
    print(f"  (vacuum energy, 4D event's antigravity continuing).")
    print()
    print(f"  Status: Approach 1 gives '32% / 68%' split but not the")
    print(f"          5%/27% within the 32%. The 5:27 ratio needs more.")

    # =========================================================================
    # Approach 2: Geometric argument for 5:27 ratio
    # =========================================================================
    print(f"\n\n  APPROACH 2: Geometric argument for 5:27 ratio")
    print(f"  {'-'*70}")
    print(f"  Within the 32% projected to 3+1D:")
    print(f"    - 5% direct (matter)")
    print(f"    - 27% indirect via 2D universes (DM)")
    print()
    print(f"  Question: why is 5% direct vs 27% indirect?")
    print()
    print(f"  Hypothesis: the ratio is set by the 3+1D event's energy")
    print(f"  that goes into matter vs into 2D-universe creation.")
    print()
    print(f"  In a 3+1D event, energy E_event is partitioned:")
    print(f"    - E_matter: rest mass of products")
    print(f"    - E_2D: energy that 'leaks' into 2D universe creation")
    print()
    print(f"  Per cascade: the 2D universe's energy is G_2D * E_event_leaked")
    print(f"  But the *back-projected* DM is G_2D * E_event_leaked / G_2D^2")
    print(f"  ... no wait, that's not right either.")
    print()
    print(f"  Let me re-examine the cascade's mass-energy bookkeeping.")
    print(f"  In cascade_model.py:")
    print(f"    2D universe's mass-energy at peak: M_2D_peak = 20 * G * M_event")
    print(f"    This is the 2D universe's INTERNAL mass-energy (in 2D's frame)")
    print(f"  In 3+1D's frame, the 2D universe's mass-energy is:")
    print(f"    M_2D_in_3plus1D = M_2D_peak / G_2D^2 ?")
    print(f"  (per cascade: 1/G is the back-projection factor)")
    print()
    print(f"  Hmm, this is getting hand-wavy. Let me just try the numbers.")

    # Try: 5%/27% = 1/5.4 = (some combinatorial formula)
    print(f"\n  Trying various combinatorial formulas for 5:27 = 1:5.4:")
    print(f"    1/5.4 = 5/27 (trivial)")
    print(f"    1/5.4 = 1/(2*2.7) = 1/2 / 2.7 = 0.5/2.7")
    print(f"    5/27 = 0.185...")
    print()

    # Try: 5/27 = (some function of cascade growth factor)
    print(f"  What if 5:27 = 1:N_cascade where N_cascade is the growth factor ratio?")
    print(f"  G_2D = 1e8 (per cascade)")
    print(f"  G_2D / 1e7 = 10.  Hmm, not 5.4.")
    print(f"  G_2D / 1.85e7 = 5.4. Random.")
    print(f"  sqrt(G_2D) = 1e4.  1e4 / 1854 = 5.4.  Also random.")
    print()
    print(f"  Status: Approach 2 doesn't find a natural 5:27 ratio.")

    # =========================================================================
    # Approach 3: Cascade-level dynamics (cumulative event budgets)
    # =========================================================================
    print(f"\n\n  APPROACH 3: Cascade-level dynamics")
    print(f"  {'-'*70}")
    print(f"  Total energy in 2D universes (cumulative over 13.8 Gyr):")
    print(f"    E_2D_total = sum over all 3+1D events of (G_2D * E_event_leaked)")
    print()
    print(f"  In our 3+1D frame, this E_2D_total projects back as DM.")
    print(f"  The 'back-projection' factor is 1/G_2D (per cascade).")
    print(f"  So DM = (1/G_2D) * E_2D_total = (1/G_2D) * G_2D * E_3plus1D_leaked")
    print(f"  = E_3plus1D_leaked")
    print()
    print(f"  Hmm, this gives DM = total energy leaked into 2D universes.")
    print(f"  But: how does that compare to the 27% observation?")
    print()
    print(f"  Let's compute E_3plus1D_leaked:")
    print(f"    E_matter = 5% * E_3plus1D (ordinary matter)")
    print(f"    E_leaked = 27% * E_3plus1D (DM back-projection, if our model is right)")
    print()
    print(f"  Ratio: E_leaked / E_matter = 27/5 = 5.4")
    print(f"  This says: 5.4x more energy goes into 2D universe creation than")
    print(f"  ends up as ordinary matter.")
    print()
    print(f"  In a typical 3+1D event (e.g., a SN):")
    print(f"    E_SN ~ 1e46 J")
    print(f"    Most of this goes into kinetic energy of ejecta (3+1D)")
    print(f"    A small fraction might create 2D universes")
    print()
    print(f"  Why would 5.4x more energy go to 2D universes?")
    print(f"  Per cascade: the 2D universe's growth factor is G_2D ~ 1e8.")
    print(f"  So 1 unit of 'leaked' 3+1D energy creates 1e8 units of 2D energy.")
    print(f"  In 2D's frame, 2D universes are MASSIVE.")
    print(f"  But in 3+1D's frame, the 2D universe's mass is 'redshifted' by G_2D^2:")
    print(f"    M_2D_in_3plus1D = M_2D_peak / G_2D^2 = (G_2D * M_event) / G_2D^2")
    print(f"    = M_event / G_2D")
    print()
    print(f"  So 1 unit of leaked 3+1D energy corresponds to 1/G_2D in DM.")
    print(f"  This is tiny: 1e-8 of M_event per event.")
    print()
    print(f"  For DM to be 5.4x more than matter, we need:")
    print(f"    (1/G_2D) * N_events * E_leaked_per_event / (1) * N_matter_events * M_matter")
    print(f"    = 5.4")
    print()
    print(f"  Solving: N_events * E_leaked_per_event / (G_2D * N_matter) = 5.4")
    print()
    print(f"  This depends on the relative frequencies of matter-creating events")
    print(f"  vs 2D-universe-creating events. Cascade says: ALL energetic events")
    print(f"  create 2D universes. So the ratio depends on event energies.")
    print()
    print(f"  Status: Approach 3 gives a *consistent* picture but doesn't")
    print(f"          uniquely predict 5:27. The 5.4 ratio depends on event")
    print(f"          frequencies in our specific universe, which is a")
    print(f"          *property of our universe*, not a *cascade prediction*.")

    # =========================================================================
    # Approach 4: Information-theoretic / entropy partition
    # =========================================================================
    print(f"\n\n  APPROACH 4: Information-theoretic / entropy partition")
    print(f"  {'-'*70}")
    print(f"  If 4D event has max entropy S_4D, the projection to 3+1D")
    print(f"  partitions entropy into:")
    print(f"    S_matter (ordinary matter's phase space)")
    print(f"    S_DM (dark matter's phase space)")
    print(f"    S_DE (dark energy's vacuum entropy)")
    print()
    print(f"  In thermal equilibrium, Omega_i ~ S_i (entropy fraction).")
    print(f"  So 5/27/68 would be entropy fractions.")
    print()
    print(f"  But: how to compute S_matter, S_DM, S_DE?")
    print(f"  - S_matter: ordinary matter has T ~ 2.7 K, n ~ 1e-7 /cm^3,")
    print(f"    so S_matter ~ V * T^3 / T_0^3 where T_0 is some reference")
    print(f"  - S_DM: similar but with DM density (5x more, T similar)")
    print(f"  - S_DE: vacuum entropy is a puzzle (Bekenstein? Gibbons-Hawking?)")
    print()
    print(f"  Hmm, S_DE is hard. If we use Gibbons-Hawking S = A/(4 l_P^2),")
    print(f"  with A = 4 pi R_H^2 and R_H = c/H_0:")
    print(f"    S_DE ~ 1e122 in natural units")
    print(f"  Compare to matter S ~ 1e90 (much smaller).")
    print(f"  So S_DE >> S_matter, S_DM, consistent with 68% > 5%, 27%.")
    print()
    print(f"  But: the *exact* ratio depends on the cosmological parameters")
    print(f"  (H_0, Omega values, etc). It's not a clean derivation.")
    print()
    print(f"  Status: Approach 4 gives qualitative agreement but no exact 5/27/68.")

    # =========================================================================
    # Approach 5: Growth-factor consistency
    # =========================================================================
    print(f"\n\n  APPROACH 5: Growth-factor consistency")
    print(f"  {'-'*70}")
    print(f"  In cascade, G_2D ~ 1e8 is the 2D universe's growth factor.")
    print(f"  This is derived (per commit 52) from 2D FRW dynamics.")
    print()
    print(f"  Question: is the 5/27/68 split *consistent* with G_2D = 1e8?")
    print()
    print(f"  Per cascade: the universal-split factor is 20 (from 1/20 = Omega_o).")
    print(f"  20 is the 'universal-split factor': how 4D -> 3+1D projection")
    print(f"  partitions the 4D energy.")
    print()
    print(f"  The 20 is POSTULATED (per universal_split_derivation.py).")
    print(f"  But: maybe it's related to G_2D?")
    print()
    print(f"  G_2D = 1e8")
    print(f"  20 = ?")
    print(f"    - 20 = 4*5 (number of cascade levels times 'spatial' factor?)")
    print(f"    - 20 = 27-7 (DM fraction minus 7?)")
    print(f"    - 20 = G_2D / 5e6 (random)")
    print()
    print(f"  Hmm, 27/68 + 5/68 = 32/68 = 8/17. Not 20.")
    print()
    print(f"  Let me try: 5% of total energy = 1/20 of 'projected' energy")
    print(f"  (where 'projected' = 32% = 5 + 27). So 5/32 = 0.156 = 1/6.4")
    print(f"  And 27/32 = 0.844 = 27/32.")
    print()
    print(f"  Within the projected energy:")
    print(f"    1/6.4 goes to matter (1/20 of total)")
    print(f"    5.4/6.4 = 27/32 goes to DM (27/100 of total)")
    print()
    print(f"  The 1/6.4 doesn't simplify to nice numbers.")
    print()
    print(f"  Status: Approach 5 doesn't find a natural relationship")
    print(f"          between G_2D = 1e8 and 5:27 ratio.")

    # =========================================================================
    # Approach 6: Cascade's universality postulate
    # =========================================================================
    print(f"\n\n  APPROACH 6: Cascade's universality postulate")
    print(f"  {'-'*70}")
    print(f"  The cascade POSTULATES (per §2.3) that the 5/27/68 split is")
    print(f"  a UNIVERSAL property of 4D -> 3+1D projection.")
    print()
    print(f"  Justification: every energetic event in our 3+1D universe creates")
    print(f"  a 2D universe. The 2D universe's growth factor G_2D = 1e8 is universal")
    print(f"  (derived from 2D FRW dynamics, which are the same for all 2D universes).")
    print()
    print(f"  So 5/27/68 should be derivable from G_2D + 4D event properties.")
    print()
    print(f"  But: 4D event properties are NOT specified by the cascade.")
    print(f"  The cascade is about the 3+1D universe's structure,")
    print(f"  given that it came from a 4D event. The 4D event's specifics")
    print(f"  (its geometry, energy, etc) are not in the cascade's framework.")
    print()
    print(f"  Therefore: 5/27/68 is a *property of the 4D event* that")
    print(f"  the cascade does NOT uniquely predict. Different 4D events")
    print(f"  could give different 5/27/68 values.")
    print()
    print(f"  Status: Approach 6 is the HONEST answer. The cascade doesn't")
    print(f"          uniquely derive 5/27/68 because it doesn't specify")
    print(f"          the 4D event's properties.")

    # =========================================================================
    # Synthesis
    # =========================================================================
    hr()
    print("SYNTHESIS")
    hr()
    print(f"\n  After trying 6 different physical approaches:")
    print()
    print(f"  1. Dimensional projection kinematics: gives 32% / 68% but not 5%/27%")
    print(f"  2. Geometric argument for 5:27: no natural 5.4 ratio found")
    print(f"  3. Cascade-level dynamics: consistent but not unique")
    print(f"  4. Information-theoretic: qualitative agreement, no exact ratio")
    print(f"  5. Growth-factor consistency: G_2D = 1e8 doesn't directly give 5:27")
    print(f"  6. Universality postulate: 5/27/68 is a *property of the 4D event*")
    print()
    print(f"  Conclusion: The cascade does NOT uniquely derive 5/27/68.")
    print(f"  The 5/27/68 split is a *property of the 4D event*,")
    print(f"  not a *prediction of the cascade* alone.")
    print()
    print(f"  This is HONEST. The cascade derives:")
    print(f"    - DM is back-projection of 2D universes (mechanism)")
    print(f"    - DE is 4D event's antigravity (mechanism)")
    print(f"    - G_2D ~ 1e8 (universal growth factor)")
    print(f"    - The 32% / 68% split (32% energetic 3+1D, 68% vacuum residue)")
    print()
    print(f"  But the 5% / 27% within the 32% requires the 4D event's specifics:")
    print(f"    - Fraction of projected energy that becomes matter vs DM")
    print(f"    - This depends on the 4D event's geometry and dynamics")
    print()
    print(f"  The 5/27/68 remains a *fit* (per commit 58) or a *postulate*.")
    print(f"  The cascade's *first-principles derivation* only gets us to")
    print(f"  32% / 68%, not the finer 5%/27% within the 32%.")
    print()
    print(f"  Status: The 5/27/68 is a LIMITATION of the cascade,")
    print(f"  not a strength. It's a fit to data, not a derivation.")


if __name__ == "__main__":
    main()
