#!/usr/bin/env python3
"""
Does 32/68 really hold at every level?

The cascade's postulate: 32/68 is universal at every cascade level.
- 3+1D: 5+27=32% energetic, 68% DE. OBSERVED.
- 2D: 5+27=32% energetic, 68% DE. POSTULATED.
- 4D: 32% energetic, 68% vacuum. POSTULATED.

This script:
1. Confirms 32/68 at 3+1D level (observation)
2. Asks: where does the 32% come from? Derivation or postulate?
3. Asks: could 32/68 break down at 2D or 4D level?
4. Honest: 32/68 is a postulate, not a derivation
"""

import math
import sys
sys.path.insert(0, ".")
sys.path.insert(0, "calculations")

from cascade_model import Constants


def hr(ch="="):
    print()
    print(ch * 78)
    print(ch * 78)


def main():
    hr()
    print("DOES 32/68 HOLD AT EVERY LEVEL OF THE CASCADE?")
    hr()

    print(f"\n  Step 1: 32/68 at 3+1D level (observation)")
    print(f"  ----------------------------------------------------------------")
    print(f"  Observed (Planck 2018):")
    print(f"    Omega_o = 0.0493 (~5%)")
    print(f"    Omega_DM = 0.265 (~27%)")
    print(f"    Omega_DE = 0.686 (~68%)")
    print()
    print(f"  5% + 27% = 32% (energetic content)")
    print(f"  68% (vacuum residue)")
    print()
    print(f"  CHECK: 32/68 at 3+1D level is OBSERVED (matches to 0.5%).")
    print(f"  This is the ONLY level where 32/68 is observationally confirmed.")

    print(f"\n\n  Step 2: 32/68 at 2D level (postulated)")
    print(f"  ----------------------------------------------------------------")
    print(f"  Per cone-shape (commits 67-70), 32/68 is universal.")
    print(f"  At 2D level:")
    print(f"    2D's energetic = 32% of 2D's mass-energy")
    print(f"    2D's vacuum = 68% of 2D's mass-energy")
    print()
    print(f"  Within 2D's 32% (per cascade's universal-split):")
    print(f"    2D's matter = 5% (the original 3+1D event in 2D's frame)")
    print(f"    2D's DM = 27% (parent's antigravity in 2D frame, per symmetry)")
    print()
    print(f"  But: 2D's '27% DM' has no direct observational check.")
    print(f"  We can only observe 2D's back-projection to 3+1D (= 3+1D's DM = 27%).")
    print(f"  We can't observe 2D's frame directly.")
    print()
    print(f"  Status: 32/68 at 2D is POSTULATED, not observed.")

    print(f"\n\n  Step 3: 32/68 at 4D level (postulated)")
    print(f"  ----------------------------------------------------------------")
    print(f"  Per cone-shape, 32/68 is universal.")
    print(f"  At 4D level:")
    print(f"    4D's energetic = 32% of 4D's mass-energy")
    print(f"    4D's vacuum = 68% of 4D's mass-energy (= our DE)")
    print()
    print(f"  Within 4D's 32%: 4D's intrinsic matter + 4D's DM")
    print(f"  (4D's m/DM/DE is 4D-specific, not 5/27/68)")
    print()
    print(f"  We can observe 4D's vacuum projection (= our DE = 68%)")
    print(f"  but we can't observe 4D's frame directly.")
    print()
    print(f"  Status: 32/68 at 4D is POSTULATED, but partially confirmed")
    print(f"  (4D's 68% vacuum = our 68% DE, which IS observed).")

    print(f"\n\n  Step 4: Where does the 32% come from? Derivation or postulate?")
    print(f"  ----------------------------------------------------------------")
    print(f"  The cascade's claim: 32/68 comes from 'dimensional-projection kinematics'.")
    print()
    print(f"  But: where exactly does 32% come from?")
    print()
    print(f"  Possible derivations:")
    print(f"    A) Geometric: 32% = 1/3.125. 1/3.125 = 8/25 = 0.32. Not clean.")
    print(f"    B) Dimensional: 32% = 1 - 68% = 1 - 2/3 = 1/3? No, 32% != 1/3.")
    print(f"    C) Combinatorial: 32/68 = 8/17. 8 = 2^3, 17 = prime. Not clean.")
    print(f"    D) Field-theoretic: 32% = 1 - 0.68. Why 0.68 specifically?")
    print(f"    E) Postulated: 32% is just a parameter of the cascade.")
    print()
    print(f"  None of A-E give a clean derivation of 32%.")
    print(f"  32/68 is the cascade's working assumption, not a first-principles derivation.")
    print()
    print(f"  The 32% might be EMPIRICALLY chosen to match observation:")
    print(f"    Observed: 3+1D's 5+27=32% energetic, 68% vacuum")
    print(f"    The cascade sets 32% as the 'universal split' to match this.")
    print(f"  Then 32% is empirical, not derived.")
    print()
    print(f"  Alternative: 32/68 might be the result of a specific projection")
    print(f"  mechanism. E.g., if the projection kinematics gives 32% energetic,")
    print(f"  that's a property of the mechanism. But the cascade doesn't")
    print(f"  derive this from a specific Lagrangian or geometric principle.")

    print(f"\n\n  Step 5: Could 32/68 break down at other levels?")
    print(f"  ----------------------------------------------------------------")
    print(f"  Yes, in principle. The 32/68 is a postulate, not a derivation.")
    print(f"  If the dimensional-projection mechanism has different kinematics")
    print(f"  at different levels, the split could be different.")
    print()
    print(f"  Scenarios where 32/68 might break down:")
    print()
    print(f"  Scenario 1: 2D's projection from 3+1D is different from 3+1D's")
    print(f"    projection from 4D. Maybe 3+1D's energetic fraction of 2D is")
    print(f"    50%, not 32%. Then 2D's energetic is 50%, vacuum is 50%.")
    print()
    print(f"  Scenario 2: 4D's projection from 5D (if 5D exists) is different.")
    print(f"    Maybe 4D's energetic is 80%, not 32%. Then 4D's 80% is much")
    print(f"    bigger than 3+1D's 32%.")
    print()
    print(f"  Scenario 3: 2D's INTERNAL DE (per G_2D derivation, Omega_DE_2D = 0.999)")
    print(f"    is 99.9%, but the cascade's external vacuum is 68%.")
    print(f"    These are different things (internal vs external).")
    print(f"    The 32/68 universality is about EXTERNAL (parent's projection),")
    print(f"    not INTERNAL (level's own dynamics).")
    print()
    print(f"  Status: 32/68 could break down at other levels.")
    print(f"  We have no way to test this observationally (we observe only 3+1D).")

    print(f"\n\n  Step 6: What does this mean for the cascade?")
    print(f"  ----------------------------------------------------------------")
    print(f"  The 32/68 universality is:")
    print(f"    - A POSTULATE of the cone-shape cascade (not a derivation)")
    print(f"    - OBSERVED at 3+1D level (matches Planck 2018)")
    print(f"    - PARTIALLY CONFIRMED at 4D level (4D's 68% = our DE)")
    print(f"    - POSTULATED at 2D level (no direct observation)")
    print()
    print(f"  If the postulate is wrong at 2D or 4D level:")
    print(f"    - 2D's 5/27 might be different (e.g., 2D has 50% matter, 50% vacuum)")
    print(f"    - 4D's energetic fraction might be different (e.g., 80% not 32%)")
    print(f"    - The cascade's universal-split would need to be re-derived")
    print()
    print(f"  If the postulate is right:")
    print(f"    - 32/68 is a true universal property of dimensional projection")
    print(f"    - The cascade's framework is robust at all levels")
    print()
    print(f"  We can't distinguish these scenarios observationally")
    print(f"  (we only see 3+1D directly).")

    print(f"\n\n  Step 7: Honest status")
    print(f"  ----------------------------------------------------------------")
    print(f"  Q: '32/68 is real means every level of cascade must have this ratio?'")
    print()
    print(f"  A: The 32/68 IS observed at 3+1D level (matches Planck 2018).")
    print(f"  But: whether 32/68 holds at OTHER levels is a POSTULATE,")
    print(f"  not a derivation. The cascade's cone-shape asserts universality,")
    print(f"  but this is an assumption, not a proven result.")
    print()
    print(f"  If 32/68 is NOT universal (e.g., 2D has different split):")
    print(f"    - 2D's DM contribution to 3+1D would be different")
    print(f"    - The cascade's mechanism for DM in 3+1D would change")
    print(f"    - The 27% DM observation would need to come from elsewhere")
    print()
    print(f"  But: we observe 27% DM in 3+1D. This is consistent with 32/68 at")
    print(f"  3+1D level + 2D back-projection. It doesn't constrain 2D's own split.")
    print()
    print(f"  Status: 32/68 is observed at 3+1D, postulated at other levels.")
    print(f"  Universality is an assumption, not a derivation.")

    # Summary
    hr()
    print("SUMMARY")
    hr()
    print(f"\n  Q: '32/68 is real means every level of cascade must have this ratio?'")
    print()
    print(f"  Honest answer: 32/68 is REAL at 3+1D (observed).")
    print(f"  Whether it's universal (at every level) is a POSTULATE, not a derivation.")
    print()
    print(f"  At 3+1D level: 32/68 confirmed (Planck 2018: 5+27=32% matter+DM, 68% DE)")
    print(f"  At 2D level: 32/68 postulated (no direct observation)")
    print(f"  At 4D level: 32/68 postulated (partially confirmed: 4D's 68% = our DE)")
    print()
    print(f"  The 32/68 universality is an assumption of the cone-shape cascade.")
    print(f"  It could in principle break down at other levels, but we can't test this.")
    print()
    print(f"  If 32/68 is truly universal:")
    print(f"    - It's a property of dimensional-projection kinematics")
    print(f"    - The cascade's framework is robust at all levels")
    print()
    print(f"  If 32/68 is level-specific:")
    print(f"    - The cascade's universality postulate is wrong")
    print(f"    - Each level has its own split (from its own dynamics)")
    print(f"    - The cascade would need to be re-derived level-by-level")
    print()
    print(f"  Status: the cascade's 32/68 universality is a working assumption,")
    print(f"  supported by the 3+1D observation but not rigorously derived")
    print(f"  for other levels. The framework is consistent at all levels,")
    print(f"  but the universality is a postulate, not a proven result.")


if __name__ == "__main__":
    main()
